export const ADD_CUSTOMER = 'ADD_CUSTOMER';
export const DELETE_CUSTOMER = 'DELETE_CUSTOMER';
export const CHANGE_CUSTOMER = 'CHANGE_CUSTOMER';

export const FETCH_CUSTOMERS = 'FETCH_CUSTOMERS';
export const FETCH_CUSTOMERS_SUCCESS = 'FETCH_CUSTOMERS_SUCCESS'; 
export const FETCH_CUSTOMERS_ERROR = 'FETCH_CUSTOMERS_ERROR'; 

export const ADD_NOTE = 'ADD_NOTE';
export const DELETE_NOTE = 'DELETE_NOTE';

export const FETCH_NOTES = 'FETCH_NOTES';
export const FETCH_NOTES_SUCCESS = 'FETCH_NOTES_SUCCESS'; 
export const FETCH_NOTES_ERROR = 'FETCH_NOTES_ERROR'; 